language: python
python:
    - "2.6"

branches:
  only:
    - master

notifications:
  email:
    - hschlichting@mozilla.com

before_install:
    - sudo apt-get -q update >/dev/null 2>&1
    - sudo apt-get -q install libevent-dev libpcre3-dev libzookeeper-dev >/dev/null 2>&1

install:
    - make build
    - make cassandra
    - make nginx
    - make zookeeper

before_script:
    - bin/supervisord
    - sleep 5
    - bin/cassandra/bin/cassandra-cli -host 127.0.0.1 --file etc/cassandra/message_schema.txt
    - bin/cassandra/bin/cassandra-cli -host 127.0.0.1 --file etc/cassandra/metadata_schema.txt

script: make test

after_script:
    - bin/supervisorctl shutdown
