language: python
python:
    - "2.6"
install: make build
script: make test

branches:
  only:
    - master

notifications:
  email:
    - hschlichting@mozilla.com

before_install:
    - sudo apt-get install libevent-dev libzmq-dev
